ngxsis.MVC/Controllers/OrganisasiController.cs
using ngxsis.Repository;
using ngxsis.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ngxsis.MVC.Controllers
{
    public class OrganisasiController : Controller
    {
        // GET: Organisasi
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int biodata_id)
        {
            return PartialView("_List", OrganisasiRepo.ByBiodataId(biodata_id));
        }

        // CREATE
        public ActionResult Create()
        {
            return PartialView("_Create", new OrganisasiViewModel());
        }

        [HttpPost]
        public ActionResult Create(OrganisasiViewModel model)
        {
            if (!ModelState.IsValid || int.Parse(model.exit_year) < int.Parse(model.entry_year))
            {
                return Json(new
                {
                    success = false,
                    message = "Invalid"
                }, JsonRequestBehavior.AllowGet);
            }

            ResponseResult result = OrganisasiRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // EDIT
        public ActionResult Edit(int id)
        {
            return PartialView("_Edit", OrganisasiRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(OrganisasiViewModel model)
        {
            if (!ModelState.IsValid || int.Parse(model.exit_year) < int.Parse(model.entry_year))
            {
                return Json(new
                {
                    success = false,
                    message = "Invalid"
                }, JsonRequestBehavior.AllowGet);
            }
            ResponseResult result = OrganisasiRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // DELETE
        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", OrganisasiRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(OrganisasiViewModel model)
        {
            ResponseResult result = OrganisasiRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsExitYearValid(string exit_year, string entry_year)
        {
            return Json(OrganisasiRepo.ValidationExitYear(exit_year, entry_year), JsonRequestBehavior.AllowGet);
        }
    }
}

ngxsis.MVC/Views/Organisasi/Index.cshtml
<div id="datadata">
</div>

@*@section Scripts{
    <script type="text/javascript">
        $('.organisasi').ready(function () {
            GetList();
        });

        function GetList() {
            biodata_id = $(this).data("id");
            $.ajax({
                url: '@Url.Action("List", "Organisasi")',
                type: 'get',
                data: { biodata_id: $(this).attr("data-id") },
                success: function (result) {
                    $("#datadata").html(result);
                }
            });
        }
    </script>
}*@

<div class="modal fade modal-create" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background: darkblue">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="background: darkblue; color: white">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-delete" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

ngxsis.MVC/Views/Organisasi/_Create.cshtml
@model ngxsis.ViewModel.OrganisasiViewModel

@using (Html.BeginForm("Create", "Organisasi", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.biodata_id)
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.entry_year, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.DropDownListFor(model => model.entry_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.entry_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.exit_year, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.DropDownListFor(model => model.exit_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.exit_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.responsibility, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.responsibility, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.responsibility, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control form-notes" } })
                            @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="btn-group col-md-offset-9">
                    <input type="button" value="Batal" class="btn btn-batal" />
                    <input type="submit" value="Simpan" class="btn btn-simpan" />
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-create").submit(function () {
        $("#biodata_id").val(biodata_id);
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil disimpan");
                    $(".modal-create").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetOrganisasi();
                }
                else {
                    //$("#form-create").validate();
                    //alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Organisasi/_Delete.cshtml
@model ngxsis.ViewModel.OrganisasiViewModel

<div>
    <dl class="dl-horizontal">
        <dt>
            <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size:100px; color:Black; text-align:center"></span>
        </dt>
        <dd>
            <font style="align-content: center"><font color="red"><font size="4">Anda yakin ingin menghapus organisasi <b>@Html.DisplayFor(model => model.name)?</b></font></font></font>
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "Organisasi", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.name)
        @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })

        <div class="row">
            <div class="btn-group col-md-offset-9">
                <input type="button" value="Tidak" class="btn btn-batal" />
                <input type="submit" value="Ya" class="btn btn-ya" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil dihapus");
                    $(".modal-delete").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetOrganisasi();
                } else
                {
                    alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-delete").modal("hide");
        //$(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-delete").modal("hide");
        //$(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Organisasi/_Edit.cshtml
@model ngxsis.ViewModel.OrganisasiViewModel

@using (Html.BeginForm("Edit", "Organisasi", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.biodata_id)
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.entry_year, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.DropDownListFor(model => model.entry_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.entry_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.exit_year, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.DropDownListFor(model => model.exit_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.exit_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.responsibility, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.responsibility, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.responsibility, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control form-notes" } })
                            @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="btn-group col-md-offset-9">
                    <input type="button" value="Batal" class="btn btn-batal" />
                    <input type="submit" value="Simpan" class="btn btn-simpan" />
                </div>
            </div>
        </div>
    </div>

}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $("#biodata_id").val(biodata_id);
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil disimpan");
                    $(".modal-create").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetOrganisasi();
                }
                else {
                    //$("#form-create").validate();
                    //alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Organisasi/_List.cshtml
@model IEnumerable<ngxsis.ViewModel.OrganisasiViewModel>

<h2>
    <font style="color: #000080"><b>Organisasi</b></font>
    <button type="button" class="btn btn-primary btn-create" id="btn-create-new" title="Tambah Organisasi">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                NAMA
            </th>
            <th>
                JABATAN
            </th>
            <th>
                PERIODE
            </th>
            <th>
                #
            </th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.entry_year) s.d. @Html.DisplayFor(modelItem => item.exit_year)
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-more dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <li><a href="#" data-container="@item.id" class="btn-edit">Ubah</a></li>
                        <li><a href="#" data-container="@item.id" class="btn-delete">Hapus</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

<script type="text/javascript">
    $("#btn-create-new").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Organisasi")',
            type: 'get',
            success: function (result) {
                $(".modal-create .modal-title").html("Tambah Organisasi");
                $(".modal-create .modal-body").html(result);
                $(".modal-pelamar").modal("hide");
                $(".modal-create").modal("show");
            }
        });
    });

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Organisasi")',
            type: 'get',
            data: { id: $(this).attr("data-container") },
            success: function (result) {
                $(".modal-create .modal-title").html("Ubah Organisasi");
                $(".modal-create .modal-body").html(result);
                $(".modal-pelamar").modal("hide");
                $(".modal-create").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Organisasi")',
            type: 'get',
            data: { id: $(this).attr("data-container") },
            success: function (result) {
                $(".modal-delete .modal-title").html("Hapus Organisasi?");
                $(".modal-delete .modal-body").html(result);
                //$(".modal-pelamar").modal("hide");
                $(".modal-delete").modal("show");
            }
        });
    });
</script>

<link rel="stylesheet" href="~/Content/Organisasi.css" />