ngxsis.MVC/Controllers/PelatihanController.cs
using ngxsis.Repository;
using ngxsis.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ngxsis.MVC.Controllers
{
    public class PelatihanController : Controller
    {
        // GET: Pelatihan
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int biodata_id)
        {
            return PartialView("_List", PelatihanRepo.ByBiodataId(biodata_id));
        }

        // CREATE
        public ActionResult Create()
        {
            ViewBag.PelatihanList = new SelectList(PelatihanRepo.PeriodAll(), "time_period_id", "time_period_name");
            return PartialView("_Create", new PelatihanViewModel());
        }

        [HttpPost]
        public ActionResult Create(PelatihanViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    success = false,
                    message = "Invalid"
                }, JsonRequestBehavior.AllowGet);
            }
            ResponseResult result = PelatihanRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // EDIT
        public ActionResult Edit(int id)
        {
            ViewBag.PelatihanList = new SelectList(PelatihanRepo.PeriodAll(), "time_period_id", "time_period_name");
            return PartialView("_Edit", PelatihanRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(PelatihanViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    success = false,
                    message = "Invalid"
                }, JsonRequestBehavior.AllowGet);
            }
            ResponseResult result = PelatihanRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // DELETE
        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", PelatihanRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(PelatihanViewModel model)
        {
            ResponseResult result = PelatihanRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

ngxsis.MVC/Views/Pelatihan/Index.cshtml
<div id="datadata">
</div>

@*@section Scripts{
    <script type="text/javascript">
        $('.pelatihan').ready(function () {
            GetList();
        });

        function GetList() {
            biodata_id = $(this).data("id");
            $.ajax({
                url: '@Url.Action("List", "Pelatihan")',
                type: 'get',
                data: { biodata_id: $(this).attr("data-id") },
                success: function (result) {
                    $("#datadata").html(result);
                }
            });
        }
    </script>
}*@

<div class="modal fade modal-create" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background: darkblue">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="background: darkblue; color: white">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-delete" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

ngxsis.MVC/Views/Pelatihan/_Create.cshtml
@model ngxsis.ViewModel.PelatihanViewModel

@using (Html.BeginForm("Create", "Pelatihan", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.biodata_id)
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.training_name, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.training_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.training_name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.organizer, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.organizer, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.organizer, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.training_month, htmlAttributes: new { @class = "control-label" })
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.training_month,
                new List<SelectListItem> {
                    new SelectListItem { Value = "1", Text = "Januari" },
                    new SelectListItem { Value = "2", Text = "Februari" },
                    new SelectListItem { Value = "3", Text = "Maret" },
                    new SelectListItem { Value = "4", Text = "April" },
                    new SelectListItem { Value = "5", Text = "Mei" },
                    new SelectListItem { Value = "6", Text = "Juni" },
                    new SelectListItem { Value = "7", Text = "Juli" },
                    new SelectListItem { Value = "8", Text = "Agustus" },
                    new SelectListItem { Value = "9", Text = "September" },
                    new SelectListItem { Value = "10", Text = "Oktober" },
                    new SelectListItem { Value = "11", Text = "November" },
                    new SelectListItem { Value = "12", Text = "Desember" }
                },
                "- Pilih Bulan -",
                new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.training_month, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.training_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.training_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.training_duration, htmlAttributes: new { @class = "control-label" })
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.training_duration, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.training_duration, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.time_period_id,
                            (IEnumerable<SelectListItem>)ViewBag.PelatihanList,
                            "- Pilih -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.time_period_id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control form-notes" } })
                            @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="btn-group col-md-offset-9">
                    <input type="button" value="Batal" class="btn btn-batal" />
                    <input type="submit" value="Simpan" class="btn btn-simpan" />
                </div>
            </div>
        </div>
    </div>

}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-create").submit(function () {
        $("#biodata_id").val(biodata_id);
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil disimpan");
                    $(".modal-create").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetPelatihan();
                }
                else {
                    $("#form-create").validate();
                    //alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Pelatihan/_Delete.cshtml
@model ngxsis.ViewModel.PelatihanViewModel

<div>
    <dl class="dl-horizontal">
        <dt>
            <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size:100px; color:Black; text-align:center"></span>
        </dt>
        <dd>
            <font style="align-content: center"><font color="red"><font size="4">Anda yakin ingin menghapus Pelatihan <b>@Html.DisplayFor(model => model.training_name)?</b></font></font></font>
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "Pelatihan", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.training_name)
        @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })

        <div class="row">
            <div class="btn-group col-md-offset-9">
                <input type="button" value="Tidak" class="btn btn-batal" />
                <input type="submit" value="Ya" class="btn btn-ya" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil dihapus");
                    $(".modal-delete").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetPelatihan();
                } else
                {
                    alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-delete").modal("hide");
        //$(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-delete").modal("hide");
        //$(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Pelatihan/_Edit.cshtml
@model ngxsis.ViewModel.PelatihanViewModel

@using (Html.BeginForm("Edit", "Pelatihan", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.user_id, new { Value = Session["userID"] })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.biodata_id)
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.training_name, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.training_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.training_name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.organizer, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.organizer, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.organizer, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.training_month, htmlAttributes: new { @class = "control-label" })
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.training_month,
                new List<SelectListItem> {
                    new SelectListItem { Value = "1", Text = "Januari" },
                    new SelectListItem { Value = "2", Text = "Februari" },
                    new SelectListItem { Value = "3", Text = "Maret" },
                    new SelectListItem { Value = "4", Text = "April" },
                    new SelectListItem { Value = "5", Text = "Mei" },
                    new SelectListItem { Value = "6", Text = "Juni" },
                    new SelectListItem { Value = "7", Text = "Juli" },
                    new SelectListItem { Value = "8", Text = "Agustus" },
                    new SelectListItem { Value = "9", Text = "September" },
                    new SelectListItem { Value = "10", Text = "Oktober" },
                    new SelectListItem { Value = "11", Text = "November" },
                    new SelectListItem { Value = "12", Text = "Desember" }
                },
                "- Pilih Bulan -",
                new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.training_month, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.training_year, new SelectList(Enumerable.Range(DateTime.Today.Year - 20, 21)),
                            "- Pilih Tahun -",
                            new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.training_year, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.training_duration, htmlAttributes: new { @class = "control-label" })
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.training_duration, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.training_duration, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.time_period_id,
                            (IEnumerable<SelectListItem>)ViewBag.PelatihanList,
                            "- Pilih -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.time_period_id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control form-notes" } })
                            @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="btn-group col-md-offset-9">
                    <input type="button" value="Batal" class="btn btn-batal" />
                    <input type="submit" value="Simpan" class="btn btn-simpan" />
                </div>
            </div>
        </div>
    </div>

}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $("#biodata_id").val(biodata_id);
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data berhasil disimpan");
                    $(".modal-create").modal("hide");
                    $(".modal-pelamar").modal("show");
                    GetPelatihan();
                }
                else {
                    $("#form-edit").validate();
                    //alert("Error! " + result.message);
                }
            }
        });
        return false;
    });

    $(".btn-batal").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });

    $(".close").click(function () {
        $(".modal-create").modal("hide");
        $(".modal-pelamar").modal("show");
    });
</script>

ngxsis.MVC/Views/Pelatihan/_List.cshtml
@model IEnumerable<ngxsis.ViewModel.PelatihanViewModel>

<h2>
    <font style="color: #000080"><b>Pelatihan</b></font>
    <button type="button" class="btn btn-primary btn-create" id="btn-create-new" title="Tambah Pelatihan">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                PELATIHAN/WORKSHOP
            </th>
            <th>
                PENYELENGGARA
            </th>
            <th>
                WAKTU
            </th>
            <th>
                DURASI
            </th>
            <th>
                #
            </th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.training_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.organizer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.training_year)-@Html.DisplayFor(modelItem => item.training_month)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.training_duration) @Html.DisplayFor(modelItem => item.time_period_name)
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-more dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <li><a href="#" data-container="@item.id" class="btn-edit">Ubah</a></li>
                        <li><a href="#" data-container="@item.id" class="btn-delete">Hapus</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

<script type="text/javascript">
    $("#btn-create-new").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Pelatihan")',
            type: 'get',
            success: function (result) {
                $(".modal-create .modal-title").html("Tambah Pelatihan");
                $(".modal-create .modal-body").html(result);
                $(".modal-pelamar").modal("hide");
                $(".modal-create").modal("show");
            }
        });
    });

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Pelatihan")',
            type: 'get',
            data: { id: $(this).attr("data-container") },
            success: function (result) {
                $(".modal-create .modal-title").html("Ubah Pelatihan");
                $(".modal-create .modal-body").html(result);
                $(".modal-pelamar").modal("hide");
                $(".modal-create").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Pelatihan")',
            type: 'get',
            data: { id: $(this).attr("data-container") },
            success: function (result) {
                $(".modal-delete .modal-title").html("Hapus Pelatihan?");
                $(".modal-delete .modal-body").html(result);
                //$(".modal-pelamar").modal("hide");
                $(".modal-delete").modal("show");
            }
        });
    });
</script>

<link rel="stylesheet" href="~/Content/Organisasi.css" />