ngxsis.MVC/Controllers/RoleController.cs
using ngxsis.Repository;
using ngxsis.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ngxsis.MVC.Controllers
{
    public class RoleController : Controller
    {
        // GET: Role
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult RoleList(string search = "", int desc=0, int page=0, int dataPerPage=10)
        {
            List<RoleViewModel> result = RoleRepo.BySearch(search, desc, page, dataPerPage);
            return PartialView("_RoleList", result);
        }
        public ActionResult Create()
        {
            return PartialView("_Create", new RoleViewModel());
        }

        public ActionResult Edit(long Id)
        {
            return PartialView("_Edit", RoleRepo.ById(Id));
        }
        public ActionResult Delete(long Id)
        {
            return PartialView("_Delete", RoleRepo.ById(Id));
        }

        [HttpPost]
        public ActionResult Create(RoleViewModel model)
        {
            ResponseResult result = RoleRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Edit(RoleViewModel model)
        {
            ResponseResult result = RoleRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Delete(RoleViewModel model)
        {
            ResponseResult result = RoleRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsNameUnique(string Name, int Id=0)
        {
            return Json(RoleRepo.ByName(Name, Id),JsonRequestBehavior.AllowGet);
        }
        public JsonResult IsCodeUnique(string Code, int Id=0)
        {
            return Json(RoleRepo.ByCode(Code, Id),JsonRequestBehavior.AllowGet);
        }
    }
}

ngxsis.MVC/Views/Role/Index.cshtml
@{
    ViewBag.Title="Peran";
}

@{
    ViewBag.UID=Session["userID"];    
    if (Session["userID"] != null && Session["roleID"] == null)
    {
        Response.Redirect("~/Account/SelectAccess"); // <-- Sesuaikan acceess bila sudah login
    }

    if (Session["userID"] == null && Session["roleID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}

<link rel="stylesheet" href="~/Content/role.css"/>
<div class="panel panel-default panel-role" style="width:100%;">
    <div class="panel-body" style="padding:0px 0px;width:100%">
    </div>
    <div id="data">
        Loading...
    </div>
</div>

<div class="modal fade modal-main" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" style="color:#ffffff;font-size:20px;" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade modal-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section scripts
{
    <script type="text/javascript">
        var page;
        var search;
        var desc;
        var maxPage;
        var dataPerPage;
            var itemCount = 0;
        $(document).ready(function () {
            page = 0;
            search = "";
            desc = 0;
            maxPage = 0;
            dataPerPage = 1;
            GetList();
        });

        function GetList() {
            
            $.ajax(
            {
                url: '@Url.Action("RoleList", "Role")',
                type: 'get',
                data: { search: search, desc: desc , page: page, dataPerPage: dataPerPage },
                success: function (result) {
                    $("#txt-search").val(search);
                    $("#data").html(result);


                    //$("#data").find("tbody").find("tr").each(function (item) {
                    //    itemCount = itemCount + 1;
                    //    console.log("itemcount=" + itemCount);
                    //});
                    //if (itemCount < dataPerPage) {
                    //    maxPage = page;
                    //    console.log("if" + itemCount + "<" + dataPerPage);
                    //} else {
                    //    maxPage = page + 1;
                    //    console.log("else");
                    //}
                }
            });
        }
        
    </script>
}

ngxsis.MVC/Views/Role/_Create.cshtml
@model ngxsis.ViewModel.RoleViewModel


@using (Html.BeginForm("Create", "Role", FormMethod.Post, new
{
    id = "form-create",
    name = "form-create"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.LoginUserId,
                new { Value = Session["userID"] })

    <div class="col-lg-12">
        @Html.ValidationSummary(true, "", new
   {
       @class = "text-danger"
   })
        <div class="container">
            <div class="row  pull-left" style="font-size:10px;text-align:left;color: #000080;margin-left:-30px;">
                @Html.LabelFor(model => model.Code, htmlAttributes: new
           {
               @class = "control-label col-md-12"
           })
            </div>


            <div class="row">
                @Html.EditorFor(model => model.Code, new
           {
               htmlAttributes = new
               {
                   @class = "form-control"
               }
           })
                @Html.ValidationMessageFor(model => model.Code, "", new
           {
               @class = "text-danger"
           })
            </div>
            <br/>

            <div class="row  pull-left" style="font-size:10px;text-align:left;color: #000080;margin-left:-30px;">
                @Html.LabelFor(model => model.Name, htmlAttributes: new
           {
               @class = "control-label col-md-12"
           })

            </div>


            <div class="row">
                @Html.EditorFor(model => model.Name, new
           {
               htmlAttributes = new
               {
                   @class = "form-control"
               }
           })
                @Html.ValidationMessageFor(model => model.Name, "", new
           {
               @class = "text-danger"
           })

            </div>

        </div>
        <br/>


        <div class="row">
            <div class="form-actions col-lg-4 pull-right">
                <div class="btn-group">
                    <button type="button" class="btn btn-warning btn-70px" data-dismiss="modal"><b>Batal</b></button>
                    <button type="submit" class="btn btn-pp btn-70px "><b>Simpan</b></button>

                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#form-create").submit(function () {
        $("#form-create").validate();
        $("#form-create").valid();
        setTimeout(Create, 100);
        return false;
    });
    function Create() {
        if ($("#form-create").valid()) {
            $.ajax(
                {
                    url: '@Url.Action("Create","Role")',
                    type: 'post',
                    data: $("#form-create").serialize(),
                    success: function (result) {
                        if (result.success) {
                            alert("Role berhasil dibuat");
                            $(".modal-main").modal("hide");
                            GetList();
                        } else {
                            //alert("Role tidak berhasil dibuat\n" + result.message);
                        }
                    }
                });
        }
    }
</script>
@Scripts.Render("~/bundles/jqueryval")

ngxsis.MVC/Views/Role/_Delete.cshtml
@model ngxsis.ViewModel.RoleViewModel

 @using (Html.BeginForm("Delete", "Role", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
 {
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Code)
    @Html.HiddenFor(model => model.Name)
    @Html.HiddenFor(model => model.LoginUserId,
                new { Value = Session["userID"] })
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
         <div class="row">
             <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                 <span class="glyphicon glyphicon-trash btn-xlg"></span>
             </div>
             <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                 <h4 style="color:#d9534f;text-align:center;">Anda yakin ingin menghapus Role <br /><b>@Html.DisplayFor(model => model.Name)</b></h4>
             </div>
         </div>
         <div class="row">
             <div class="form-actions col-lg-4 col-md-4 col-sm-4 col-xs-4 pull-right">
                 <div class="btn-group">
                     <button type="button" class="btn btn-warning btn-70px" data-dismiss="modal"><b>Tidak</b></button>
                     <button type="submit" class="btn btn-danger btn-70px"><b>Ya</b></button>
                 </div>
             </div>
         </div>
     </div> 
    }

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax(
            {
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Pengguna berhasil dihapus\nNama Pengguna : " + result.entity.Name);
                        GetList();
                        $(".modal-delete").modal("hide");
                        
                    } else {
                        alert("Proses penghapusan gagal\n" + result.message);
                    }
                }
            });
        return false;
    });
</script>
@Scripts.Render("~/bundles/jqueryval")

ngxsis.MVC/Views/Role/_Edit.cshtml
@model ngxsis.ViewModel.RoleViewModel


@using(Html.BeginForm("Edit","Role",FormMethod.Post,new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="col-lg-12">
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.LoginUserId, new { Value = Session["userID"] })
    <div class="form-group">
        @Html.ValidationSummary(true,"",new
   {
       @class = "text-danger"
   })

            <div>
                <div class="row" style="font-size:10px;text-align:left;color: #000080;margin-left:-30px;">
                    @Html.LabelFor(model => model.Code,htmlAttributes: new
               {
                   @class = "control-label col-md-12"
               })
                </div>
                <div class="row">

                    @Html.EditorFor(model => model.Code,new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control"
                   }
               })
                    @Html.ValidationMessageFor(model => model.Code,"",new
               {
                   @class = "text-danger"
               })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div>
                <div class="row" style="font-size:10px;text-align:left;color: #000080;margin-left:-30px;">
                    @Html.LabelFor(model => model.Name,htmlAttributes: new
               {
                   @class = "control-label col-md-5"
               })

                </div>
                <div class="row">
                    @Html.EditorFor(model => model.Name,new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control"
                   }
               })
                    @Html.ValidationMessageFor(model => model.Name,"",new
               {
                   @class = "text-danger"
               })

                </div>
            </div>
        </div>
        <div class="row">

            <div class="form-actions col-lg-4 pull-right">
                <div class="btn-group">
                    <button type="button" class="btn btn-warning btn-70px" data-dismiss="modal"><b>Batal</b></button>
                    <button type="button" class="btn btn-pp btn-70px btn-simpan" onclick="simpan();"><b>Simpan</b></button>

                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    function simpan()
    {
        $("#form-edit").valid();
        setTimeout(validateForm, 100);
    }
    function validateForm()
    {
        
        $("#form-edit").validate();
        if ($("#form-edit").valid()) {
            console.log("valid" + $("#form-edit").valid());
            submited = false;
        } else
        {
            console.log("invalid")
            submited = true;
        }

        if (submited) {
            console.log("submited true");
        } else {
            $.ajax(
            {
                url: '@Url.Action("Edit","Role")',
                type: 'post',
                data: $("#form-edit").serialize(),
                success: function (result) {
                    if (result.success) {
                        console.log("submited false, submited true")
                        alert("Role berhasil diubah");
                        $(".modal-main").modal("hide");
                        GetList();
                        submited = true;
                    } else {
                        //alert("Role tidak berhasil dibuat\n" + result.message);
                    }
                }
            });
        }
       
        return false;


    }
    $("#form-edit").submit(function () {
        
        //alert("Data tida valid")
    });
</script>
@Scripts.Render("~/bundles/jqueryval")

ngxsis.MVC/Views/Role/_RoleList.cshtml
@model IEnumerable<ngxsis.ViewModel.RoleViewModel>
<div class="container" style="margin-top:2%;">


    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <div class="input-group" style="width:100%;">
                <input type="text" id="txt-search" class="form-control" style="" placeholder="Cari">
                <span class="input-group-btn">
                    <button class="btn btn-clear" style="height:45px;color:#000080;margin-left:-35px;padding:0px 10px 2px 0px;background-color:transparent;font-size:20px;" type="button"><b>&times;</b></button>
                    <button class="btn btn-pp btn-search" style="height:45px;" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                </span>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-left:0px;text-align:right;margin-top:5px;">
            <div class="btn-group btn-trans" style="margin-left:12px;" role="group" aria-label="...">
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle btn-trans  btn-lg " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-sort"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right btn-link-a">
                        <li class="dropdown-header dh">Order</li>
                        <li><a href="javascript:void(0)" class="btn-link sort-asc">Ascending</a></li>
                        <li><a href="javascript:void(0)" class="btn-link sort-desc">Descending</a></li>
                    </ul>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle btn-trans  btn-lg " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-align-justify"></span>
                    </button>
                    <ul class="dropdown-menu btn-link-a">
                        <li class="dropdown-header dh">Row Per Page</li>
                        <li><a href="javascript:void(0)" class="btn-link btn-list" data-container="10">10</a></li>
                        <li><a href="javascript:void(0)" class="btn-link btn-list" data-container="20">20</a></li>
                        <li><a href="javascript:void(0)" class="btn-link btn-list" data-container="30">30</a></li>
                        <li><a href="javascript:void(0)" class="btn-link btn-list" data-container="40">40</a></li>
                        <li><a href="javascript:void(0)" class="btn-link btn-list" data-container="50">50</a></li>
                    </ul>
                </div>
                <button type="button" class="btn btn-trans btn-lg btn-create-new"><span class="glyphicon glyphicon-plus-sign"></span></button>
            </div>
        </div>
    </div>
    <hr style="border-bottom-width: 4px;
    border-bottom-style: solid;
    border-bottom-color: #000080;
    margin-bottom:3px;
    margin-top:0px" />
    <hr style="border-bottom-width: 2px;
    border-bottom-style: solid;
    border-bottom-color: #000080;
    margin-top:10px;" />

    <table class="table table-striped" style="font-size:small;">
        <thead>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>

                <th style="text-align:right;"><b style="margin-right:70px;">#</b></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-left">
                        <div>
                            @Html.DisplayFor(modelItem => item.Code)

                        </div>
                    </td>
                    <td class="text-left">
                        <div>
                            @Html.DisplayFor(modelItem => item.Name)

                        </div>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-primary btn-pp"><b>More</b></button>
                            <button type="button" class="btn dropdown-toggle btn-pp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu btn-link-a">
                                <li><a href="javascript:void(0)" class="btn-link-ubah" data-value="@item.Id">Ubah</a></li>
                                <li><a href="javascript:void(0)" class="btn-link-hapus" data-value="@item.Id">Hapus</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm btn-pill pull-right btn-next" onclick="plus()"><b>Next &#8594;</b></button>
                    <button type="button" class="btn btn-primary btn-sm btn-pill pull-right btn-prev" onclick="min()"><b>&#8592; Previous</b></button>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<script type="text/javascript">

    $(document).ready(function ()
    {
        itemCount = 0;
        $("#data").find("tbody").find("tr").each(function (item) {
            itemCount = itemCount + 1;
        });
        if (itemCount < dataPerPage) {
            maxPage = page;
        } else {
            maxPage = page + 1;
        }
        if (page == 0) {
            $(".btn-prev").hide();
        } else
        {
            $(".btn-prev").show();
        }
        if (page == maxPage) {
            $(".btn-next").hide();
        } else
        {
            $(".btn-next").show();
        }
    });
    /*ROW PER PAGE*/
    $(".btn-list").click(function ()
    {
        page=0;
        dataPerPage = $(this).attr("data-container");
        GetList();
    });
    /*GO TO PREVIOUS PAGE*/
    function min () {
        if (page > 0) {
            page = page - 1;
        }
        GetList();
    };
    /*GO TO NEXT PAGE*/
    function plus () {
        if (page < maxPage) {
            page = page + 1;
        }
        GetList();
    };

    /*SHOW DATA BY SEARCH*/
    $(".btn-search").click(function () {
        desc = 0;
        page = 0;
        search = $("#txt-search").val();
        GetList();
    });

    /*SORT ASCENDING*/
    $(".sort-asc").click(function () {
        desc = 0;
        page = 0;
        GetList();
    });

    /*SORT DESCENDING*/
    $(".sort-desc").click(function () {
        desc = 1;
        page = 0;
        GetList();
    });

    /*CLEAR SEARCH*/
    $(".btn-clear").click(function () {
        page = 0;
        search="";
        GetList();
    });

    /*ADD NEW DATA*/
    $(".btn-create-new").click(function () {
        $.ajax(
            {
                url: '@Url.Action("Create", "Role")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Tambah Role");
                    $(".modal-body").html(result);
                    $(".modal-main").modal("show");
                }
            });

    });
    /*EDIT DATA*/
    var submited = true;;
    $(".btn-link-ubah").click(function () {
        $.ajax(
            {
                url: '@Url.Action("Edit", "Role")',
                type: 'get',
                data: { Id: $(this).data("value") },
                success: function (result) {
                    $(".modal-main .modal-title").html("Ubah Role");
                    $(".modal-main .modal-body").html(result);
                    $(".modal-main").modal("show");
                    submited = false;
                }
            });


    });
    /*DELETE DATA*/
    $(".btn-link-hapus").click(function () {
        $.ajax(
            {
                url: '@Url.Action("Delete", "Role")',
                type: 'get',
                data: { id: $(this).data("value") },
                success: function (result) {
                    $(".modal-delete .modal-title").html("Hapus Role ?");
                    $(".modal-delete .modal-body").html(result);
                    $(".modal-delete").modal("show");
                }
            });

    });
</script>